---

- name: HIGH | UBTU-22-671010 | PATCH | Ubuntu 22.04 LTS must implement NIST FIPS-validated cryptography to protect classified information
  when: ubtu22stig_671010
  tags:
    - UBTU-22-671010
    - CAT1
    - CCI-002450
    - SRG-OS-000396-GPOS-00176
    - SRG-OS-000478-GPOS-00223
    - SV-260650r987791_rule
    - V-260650
    - NIST800-53R4_SC-13
    - fips
  vars:
    warn_control_id: 'HIGH | UBTU-22-671010'
  block:
    - name: HIGH | UBTU-22-671010 | PATCH | Ubuntu 22.04 LTS must implement NIST FIPS-validated cryptography to protect classified information | Enable FIPS
      when:
        - ubtu22stig_subscribed
        - ubtu22stig_disruption_high
      ansible.builtin.lineinfile:
        path: /proc/sys/crypto/fips_enabled
        create: true
        regexp: 0
        line: 1
        mode: 'ugo-wx'

    - name: HIGH | UBTU-22-671010 | WARN | Ubuntu 22.04 LTS must implement NIST FIPS-validated cryptography to protect classified information | Warning
      when:
        - not ubtu22stig_subscribed
        - not ubtu22stig_disruption_high
      ansible.builtin.debug:
        msg: "Warning!! - Unable carry out UBTU-22-671010 for FIPS enablement, System is not subscribed"

    - name: HIGH | UBTU-22-671010 | WARN | Ubuntu 22.04 LTS must implement NIST FIPS-validated cryptography to protect classified information | Warning
      when:
        - not ubtu22stig_subscribed
        - not ubtu22stig_disruption_high
      ansible.builtin.import_tasks:
        file: warning_facts.yml
