---

- name: HIGH | UBTU-22-211015 | PATCH | Ubuntu 22.04 LTS must disable the x86 Ctrl-Alt-Delete key sequence.
  when: ubtu22stig_211015
  tags:
    - UBTU-22-211015
    - CAT1
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-260469r991589_rule
    - V-260469
    - NIST800-53R4_CM-6
    - compliance
  ansible.builtin.systemd:
    name: ctrl-alt-del.target
    masked: true
  notify: Systemd_daemon_reload

- name: HIGH | UBTU-22-212010 | PATCH | Ubuntu 22.04 LTS, when booted, must require authentication upon booting into single-user and maintenance modes.
  when:
    - ubtu22stig_212010
    - ubtu22stig_set_bootloader_password
  tags:
    - UBTU-22-212010
    - CAT1
    - CCI-000366
    - SRG-OS-000080-GPOS-00048
    - SV-260470r958472_rule
    - V-260470
    - NIST800-53R4_AC-3
    - bootloader
  block:
    - name: HIGH | UBTU-22-212010 | PATCH | Ubuntu 22.04 LTS, when booted, must require authentication upon booting into single-user and maintenance modes.
      ansible.builtin.lineinfile:
        path: /etc/grub.d/40_custom
        regex: "{{ item.regex }}"
        line: "{{ item.line }}"
      loop:
        - { regex: '^set superusers=', line: 'set superusers="root"' }
        - { regex: '^password_pbkdf2 root', line: 'password_pbkdf2 root {{ ubtu22stig_bootloader_password_hash }}' }
      notify: Update_grub

    - name: HIGH | UBTU-22-212010 | PATCH | Ubuntu 22.04 LTS, when booted, must require authentication upon booting into single-user and maintenance modes.
      when: not ubtu22stig_ask_passwd_to_boot
      ansible.builtin.lineinfile:
        path: "/etc/grub.d/10_linux"
        regexp: '(^CLASS="--class gnu-linux --class gnu --class os).*"$'
        line: '\g<1> --unrestricted"'
        backrefs: true
      notify: Update_grub

- name: HIGH | UBTU-22-215030 | PATCH | Ubuntu 22.04 LTS must not have the "rsh-server" package installed.
  when: ubtu22stig_215030
  tags:
    - UBTU-22-215030
    - CAT1
    - CCI-000381
    - SRG-OS-000095-GPOS-00049
    - SV-260482r958478_rule
    - V-260482
    - NIST800-53R4_CM-7
    - packages
  ansible.builtin.package:
    name: rsh-server
    state: absent
    purge: "{{ ubtu22stig_purge_apt }}"

- name: HIGH | UBTU-22-215035 | PATCH | Ubuntu 22.04 LTS must not have the "telnet" package installed.
  when: ubtu22stig_215035
  tags:
    - UBTU-22-215035
    - CAT1
    - CCI-000197
    - SRG-OS-000074-GPOS-00042
    - SV-260483r987796_rule
    - V-260483
    - NIST800-53R4_IA-5
    - packages
  ansible.builtin.package:
    name: telnet
    state: absent
    purge: "{{ ubtu22stig_purge_apt }}"
