---

- name: HIGH | UBTU-22-255010 | PATCH | Ubuntu 22.04 LTS must have SSH installed.
  when:
    - ubtu22stig_255010
    - "'openssh-server' not in ansible_facts.packages"
  tags:
    - UBTU-22-255010
    - CAT1
    - CCI-002418
    - CCI-002420
    - CCI-002422
    - SRG-OS-000423-GPOS-00187
    - SRG-OS-000425-GPOS-00189
    - SRG-OS-000426-GPOS-00190
    - SV-260523r958908_rule
    - V-260523
    - NIST800-53R4_SC-8
    - ssh
  ansible.builtin.package:
    name: openssh-server
    state: present

- name: HIGH | UBTU-22-255015 | PATCH | Ubuntu 22.04 LTS must use SSH to protect the confidentiality and integrity of transmitted information.
  when: ubtu22stig_255015
  tags:
    - UBTU-22-255015
    - CAT1
    - CCI-002418
    - CCI-002420
    - CCI-002422
    - SRG-OS-000423-GPOS-00187
    - SRG-OS-000425-GPOS-00189
    - SRG-OS-000426-GPOS-00190
    - SV-260524r958908_rule
    - V-260524
    - NIST800-53R4_SC-8
    - ssh
  ansible.builtin.systemd:
    name: ssh
    state: started
    enabled: true

- name: HIGH | UBTU-22-255025 | PATCH | Ubuntu 22.04 LTS must not allow unattended or automatic login via SSH.
  when: ubtu22stig_255025
  tags:
    - UBTU-22-255025
    - CAT1
    - CCI-000366
    - SRG-OS-000480-GPOS-00229
    - SV-260526r991591_rule
    - V-260526
    - NIST800-53R4_CM-6
    - ssh
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regex: "{{ item.regex }}"
    line: "{{ item.line }}"
    validate: 'sshd -t -f %s'
  loop:
    - { regex: '^\s*(#|)PermitEmptyPasswords', line: 'PermitEmptyPasswords no'}
    - { regex: '^\s*(#|)PermitUserEnvironment', line: 'PermitUserEnvironment no'}
  notify: Restart_ssh

- name: HIGH | UBTU-22-255040 | PATCH |  Ubuntu 22.04 LTS must be configured so that remote X connections are disabled, unless to fulfill documented and validated mission requirements.
  when: ubtu22stig_255040
  tags:
    - UBTU-22-255040
    - CAT1
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-260529r991589_rule
    - V-260529
    - NIST800-53R4_CM-6
    - ssh
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regex: ^\s*(#|)X11Forwarding
    line: X11Forwarding no
    validate: 'sshd -t -f %s'
  notify: Restart_ssh
