---

- name: HIGH | UBTU-22-432015 | PATCH | Ubuntu 22.04 LTS must ensure only users who need access to security functions are part of sudo group.
  when: ubtu22stig_432015
  tags:
    - UBTU-22-432015
    - CAT1
    - CCI-001084
    - SRG-OS-000134-GPOS-00068
    - SV-260559r958518_rule
    - V-260559
    - NIST800-53R4_SC-3
    - sudo
  vars:
    warn_control_id: 'HIGH | UBTU-22-432015'
  block:
    - name: HIGH | UBTU-22-432015 | AUDIT | Ubuntu 22.04 LTS must ensure only users who need access to security functions are part of sudo group. | get group member
      ansible.builtin.shell: "grep sudo /etc/group | awk -F: '{print $NF}'"
      changed_when: false
      failed_when: discovered_sudo_group_users.rc not in [ 0, 1 ]
      register: discovered_sudo_group_users

    - name: HIGH | UBTU-22-432015 | AUDIT | Ubuntu 22.04 LTS must ensure only users who need access to security functions are part of sudo group. | Remove members
      ansible.builtin.set_fact:
        discovered_sudo_group_users_list: "{{ discovered_sudo_group_users.stdout | split(',') }} "

    - name: HIGH | UBTU-22-432015 | PATCH | Ubuntu 22.04 LTS must ensure only users who need access to security functions are part of sudo group. | Ensure member exist
      ansible.builtin.user:
        name: "{{ item }}"
        append: true
        groups: sudo
      loop: "{{ ubtu22stig_sudo_group_required }}"

    - name: HIGH | UBTU-22-432015 | AUDIT | Ubuntu 22.04 LTS must ensure only users who need access to security functions are part of sudo group. | Compare existing to required
      ansible.builtin.set_fact:
        sudo_group_members_not_required: "{{ discovered_sudo_group_users_list | difference(ubtu22stig_sudo_group_required) }}"

    - name: HIGH | UBTU-22-432015 | PATCH | Ubuntu 22.04 LTS must ensure only users who need access to security functions are part of sudo group. | Remove user not in required list
      when: ubtu22stig_disruption_high
      ansible.builtin.command: gpasswd -d "{{ item }}" sudo
      loop: "{{ sudo_group_members_not_required }}"
      changed_when: true

    - name: HIGH | UBTU-22-432015 | WARN | Ubuntu 22.04 LTS must ensure only users who need access to security functions are part of sudo group. | Warning
      when:
        - not ubtu22stig_disruption_high
        - sudo_group_members_not_required.stdout is defined
      ansible.builtin.debug:
        msg: "Warning!! The following users {{ sudo_group_members_not_required }} have been found in the sudo group but not part of the 'ubtu22stig_sudo_group_required' variable"

    - name: HIGH | UBTU-22-432015 | WARN | Ubuntu 22.04 LTS must ensure only users who need access to security functions are part of sudo group. | warn_count
      when:
        - not ubtu22stig_disruption_high
        - sudo_group_members_not_required.stdout is defined
      ansible.builtin.import_tasks:
        file: warning_facts.yml
