---

- name: MEDIUM | UBTU-22-215010 | PATCH | Ubuntu 22.04 LTS must have the "libpam-pwquality" package installed.
  when: ubtu22stig_215010
  tags:
    - UBTU-22-215010
    - CAT2
    - CCI-000366
    - SRG-OS-000480-GPOS-00225
    - SV-260478r991587_rule
    - V-260478
    - NIST800-53R4_CM-6
    - packages
  ansible.builtin.package:
    name: libpam-pwquality
    state: present
