---

- name: MEDIUM | UBTU-22-214015 | PATCH | Ubuntu 22.04 LTS must be configured so that the Advance Package Tool (APT) removes all software components after updated versions have been installed.
  when: ubtu22stig_214015
  tags:
    - UBTU-22-214015
    - CAT2
    - CCI-002617
    - SRG-OS-000437-GPOS-00194
    - SV-260477r958936_rule
    - V-260477
    - NIST800-53R4_SI-2
    - apt
  ansible.builtin.lineinfile:
    path: /etc/apt/apt.conf.d/50-unattended-upgrades
    create: true
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    mode: 'go-rwx'
  loop:
    - {regexp: 'Unattended-Upgrade::Remove-Unused-Kernel-Packages', line: 'Unattended-Upgrade::Remove-Unused-Kernel-Packages "true";'}
    - {regexp: 'Unattended-Upgrade::Remove-Unused-Dependencies', line: 'Unattended-Upgrade::Remove-Unused-Dependencies "true";'}
