---

- name: MEDIUM | UBTU-22-651010 | PATCH | Ubuntu 22.04 LTS must use a file integrity tool to verify correct operation of all security functions.
  when: ubtu22stig_651010
  tags:
    - UBTU-22-651010
    - CAT2
    - CCI-002696
    - SRG-OS-000445-GPOS-00199
    - SV-260582r958944_rule
    - V-260582
    - NIST800-53R4_SI-6
    - aide
  ansible.builtin.package:
    name: aide
    state: present

- name: MEDIUM | UBTU-22-651015 | PATCH | Ubuntu 22.04 LTS must configure AIDE to perform file integrity checking on the file system.
  when:
    - ubtu22stig_651015
    - ubtu22stig_disruption_high
    - ubtu22stig_allow_aide_check
  tags:
    - UBTU-22-651015
    - CAT2
    - CCI-002696
    - SRG-OS-000445-GPOS-00199
    - SV-260583r958944_rule
    - V-260583
    - NIST800-53R4_SI-6
    - aide
  block:
    - name: MEDIUM | UBTU-22-651015 | AUDIT | Ubuntu 22.04 LTS must configure AIDE to perform file integrity checking on the file system. | Get DB file
      ansible.builtin.shell: grep -E ^database_in /etc/aide/aide.conf | cut -d ':' -f2
      changed_when: false
      failed_when: discovered_aide_db_file.rc not in [ 0, 1 ]
      register: discovered_aide_db_file

    - name: MEDIUM | UBTU-22-651015 | AUDIT | Ubuntu 22.04 LTS must configure AIDE to perform file integrity checking on the file system. | Get DB file
      ansible.builtin.stat:
        path: "{{ discovered_aide_db_file.stdout }}"
      register: discovered_aide_db_present

    - name: MEDIUM | UBTU-22-651015 | PATCH | Ubuntu 22.04 LTS must configure AIDE to perform file integrity checking on the file system. | Run aide check
      when: discovered_aide_db_present.stat.exists
      ansible.builtin.command: aide -c /etc/aide/aide.conf --check
      changed_when: false
      failed_when: discovered_aide_check.rc not in [ 0, 7 ]
      register: discovered_aide_check

    - name: MEDIUM | UBTU-22-651015 | PATCH | Ubuntu 22.04 LTS must configure AIDE to perform file integrity checking on the file system. | Initiate aide DB
      when: not discovered_aide_db_present.stat.exists or discovered_aide_check.rc != 0
      ansible.builtin.command: aideinit
      changed_when: true

- name: MEDIUM | UBTU-22-651020 | PATCH | Ubuntu 22.04 LTS must notify designated personnel if baseline configurations are changed in an unauthorized manner. The file integrity tool must notify the system administrator when changes to the baseline configuration or anomalies in the operation of any security functions are discovered.
  when: ubtu22stig_651020
  tags:
    - UBTU-22-651020
    - CAT2
    - CCI-001744
    - CCI-002702
    - SRG-OS-000363-GPOS-00150
    - SRG-OS-000447-GPOS-00201
    - SV-260584r958794_rule
    - V-260584
    - NIST800-53R4_CM-3
    - NIST800-53R4_SI-6
    - aide
  ansible.builtin.lineinfile:
    path: /etc/default/aide
    regexp: (?i)^(#|)silentreports=
    line: SILENTREPORTS=no

- name: MEDIUM | UBTU-22-651025 | PATCH | Ubuntu 22.04 LTS must be configured so that the script that runs each 30 days or less to check file integrity is the default.
  when: ubtu22stig_651025
  tags:
    - UBTU-22-651025
    - CAT2
    - CCI-002699
    - SRG-OS-000446-GPOS-00200
    - SV-260585r958946_rule
    - V-260585
    - NIST800-53R4_SI-6
    - aide
  block:
    - name: MEDIUM | UBTU-22-651025 | AUDIT | Ubuntu 22.04 LTS must be configured so that the script that runs each 30 days or less to check file integrity is the default. | capture sha1sum
      ansible.builtin.shell: sha1sum /etc/cron.daily/aide /etc/cron.monthly/aide 2>/dev/null
      changed_when: false
      failed_when: discovered_cron_script_sha1.rc not in [ 0, 1 ]
      register: discovered_cron_script_sha1

    - name: MEDIUM | UBTU-22-651025 | PATCH | Ubuntu 22.04 LTS must be configured so that the script that runs each 30 days or less to check file integrity is the default. | replace if needed
      when: "'b71bb2cafaedf15ec3ac2f566f209d3260a37af0  /etc/cron' not in discovered_cron_script_sha1.stdout"
      ansible.builtin.shell: |
        apt download aide-common; dpkg-deb --fsys-tarfile /tmp/aide-common_*.deb | sudo tar -x ./usr/share/aide/config/cron.daily/aide -C /; cp -f /usr/share/aide/config/cron.daily/aide /etc/cron.daily/aide
      changed_when: true
      args:
        chdir: /tmp

- name: MEDIUM | UBTU-22-651030 | PATCH | Ubuntu 22.04 LTS must use cryptographic mechanisms to protect the integrity of audit tools.
  when: ubtu22stig_651030
  tags:
    - UBTU-22-651030
    - CAT2
    - CCI-001496
    - SRG-OS-000278-GPOS-00108
    - SV-260586r991567_rule
    - V-260586
    - NIST800-53R4_AU-9
    - aide
  ansible.builtin.lineinfile:
    path: /etc/aide/aide.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.regexp }} {{ item.line }}"
  loop:
    - { regexp: '/sbin/auditctl', line: 'p+i+n+u+g+s+b+acl+xattrs+sha512' }
    - { regexp: '/sbin/auditd', line: 'p+i+n+u+g+s+b+acl+xattrs+sha512' }
    - { regexp: '/sbin/ausearch', line: 'p+i+n+u+g+s+b+acl+xattrs+sha512' }
    - { regexp: '/sbin/aureport', line: 'p+i+n+u+g+s+b+acl+xattrs+sha512' }
    - { regexp: '/sbin/autrace', line: 'p+i+n+u+g+s+b+acl+xattrs+sha512' }
    - { regexp: '/sbin/audispd', line: 'p+i+n+u+g+s+b+acl+xattrs+sha512' }
    - { regexp: '/sbin/augenrules', line: 'p+i+n+u+g+s+b+acl+xattrs+sha512' }
