---

- name: MEDIUM | UBTU-22-271010 | PATCH | Ubuntu 22.04 LTS must enable the graphical user logon banner to display the Standard Mandatory DOD Notice and Consent Banner before granting local access to the system via a graphical user logon.
  when:
    - ubtu22stig_271010
    - ubtu22stig_gui
  tags:
    - UBTU-22-271010
    - CAT2
    - CCI-000048
    - SRG-OS-000023-GPOS-00006
    - SV-260535r958390_rule
    - V-260535
    - NIST800-53R4_AC-8
    - gnome
  community.general.ini_file:
    path: /etc/gdm3/greeter.dconf-defaults
    section: 'org/gnome/login-screen'
    option: banner-message-enable
    value: 'true'
    mode: 'go-wx'
  notify:
    - Update_dconf
    - Restart_gdm3

- name: MEDIUM | UBTU-22-271015 | PATCH | Ubuntu 22.04 LTS must display the Standard Mandatory DOD Notice and Consent Banner before granting local access to the system via a graphical user logon.
  when:
    - ubtu22stig_271015
    - ubtu22stig_gui
  tags:
    - UBTU-22-271015
    - CAT2
    - CCI-000048
    - SRG-OS-000023-GPOS-00006
    - SV-260536r958390_rule
    - V-260536
    - NIST800-53R4_AC-8
    - gnome
  community.general.ini_file:
    path: /etc/gdm3/greeter.dconf-defaults
    section: 'org/gnome/login-screen'
    option: banner-message-text
    value: "{{ ubtu22stig_logon_banner | join('\n') }}"
    mode: 'go-wx'
  notify:
    - Update_dconf
    - Restart_gdm3

- name: MEDIUM | UBTU-22-271020 | PATCH | Ubuntu 22.04 LTS must retain a user's session lock until that user reestablishes access using established identification and authentication procedures.
  when:
    - ubtu22stig_271020
    - ubtu22stig_gui
  tags:
    - UBTU-22-271020
    - CAT2
    - CCI-000056
    - SRG-OS-000028-GPOS-00009
    - SV-260537r958400_rule
    - V-260537
    - NIST800-53R4_AC-11
    - gnome
  ansible.builtin.command: gsettings set org.gnome.desktop.screensaver lock-enabled true
  changed_when: true

- name: MEDIUM | UBTU-22-271025 | PATCH | Ubuntu 22.04 LTS must initiate a graphical session lock after 15 minutes of inactivity.
  when:
    - ubtu22stig_271025
    - ubtu22stig_gui
  tags:
    - UBTU-22-271025
    - CAT2
    - CCI-000056
    - SRG-OS-000029-GPOS-00010
    - SV-260538r958402_rule
    - V-260538
    - NIST800-53R4_AC-11
    - gnome
  block:
    - name: MEDIUM | UBTU-22-271025 | PATCH | Ubuntu 22.04 LTS must initiate a graphical session lock after 15 minutes of inactivity. | get lock-enabled
      ansible.builtin.command: gsettings get org.gnome.desktop.screensaver lock-enabled
      changed_when: false
      failed_when: discovered_gnome_screensaver_lock_enabled.rc not in [ 0, 1 ]
      register: discovered_gnome_screensaver_lock_enabled

    - name: MEDIUM | UBTU-22-271025 | PATCH | Ubuntu 22.04 LTS must initiate a graphical session lock after 15 minutes of inactivity. | set lock-enabled
      when: "'true' not in discovered_gnome_screensaver_lock_enabled.stdout"
      ansible.builtin.command: gsettings set org.gnome.desktop.screensaver lock-enabled true
      changed_when: true

    - name: MEDIUM | UBTU-22-271025 | PATCH | Ubuntu 22.04 LTS must initiate a graphical session lock after 15 minutes of inactivity. | get lock-delay
      ansible.builtin.command: gsettings get org.gnome.desktop.screensaver lock-delay
      changed_when: false
      failed_when: discovered_gnome_screensaver_lock_delay.rc not in [ 0, 1 ]
      register: discovered_gnome_screensaver_lock_delay

    - name: MEDIUM | UBTU-22-271025 | PATCH | Ubuntu 22.04 LTS must initiate a graphical session lock after 15 minutes of inactivity. | set lock-delay
      when: "'uint32' not in discovered_gnome_screensaver_lock_delay.stdout"
      ansible.builtin.command: gsettings set org.gnome.desktop.screensaver lock-delay 0
      changed_when: true

    - name: MEDIUM | UBTU-22-271025 | PATCH | Ubuntu 22.04 LTS must initiate a graphical session lock after 15 minutes of inactivity. | get idle-delay
      ansible.builtin.command: gsettings get org.gnome.desktop.session idle-delay
      changed_when: false
      failed_when: discovered_gnome_session_idle_delay.rc not in [ 0, 1 ]
      register: discovered_gnome_session_idle_delay

    - name: MEDIUM | UBTU-22-271025 | PATCH | Ubuntu 22.04 LTS must initiate a graphical session lock after 15 minutes of inactivity. | set idle-delay
      when: "'uint32 900' not in discovered_gnome_session_idle_delay.stdout"
      ansible.builtin.command: gsettings set org.gnome.desktop.session idle-delay 900
      changed_when: true
