---

- name: MEDIUM | UBTU-22-255020 | PATCH | Ubuntu 22.04 LTS must display the Standard Mandatory DOD Notice and Consent Banner before granting any local or remote connection to the system.
  when: ubtu22stig_255020
  tags:
    - UBTU-22-255020
    - CAT2
    - CCI-000048
    - CCI-001384
    - CCI-001385
    - CCI-001386
    - CCI-001387
    - CCI-001388
    - SRG-OS-000023-GPOS-00006
    - SRG-OS-000228-GPOS-00088
    - SV-260525r958390_rule
    - V-260525
    - NIST800-53R4_AC-8
  block:
    - name: MEDIUM | UBTU-22-255020 | PATCH | Ubuntu 22.04 LTS must display the Standard Mandatory DOD Notice and Consent Banner before granting any local or remote connection to the system. | sshd_config
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '(?i)^#?Banner'
        line: 'Banner /etc/issue.net'
      notify: Restart_ssh

    - name: MEDIUM | UBTU-22-255020 | PATCH | Ubuntu 22.04 LTS must display the Standard Mandatory DOD Notice and Consent Banner before granting any local or remote connection to the system. | Set banner message
      ansible.builtin.template:
        src: etc/issue.net.j2
        dest: /etc/issue.net
        group: root
        mode: 'go-wx'
        owner: root

- name: MEDIUM | UBTU-22-255030 | PATCH | Ubuntu 22.04 LTS must be configured so that all network connections associated with SSH traffic terminate after becoming unresponsive.
  when: ubtu22stig_255030
  tags:
    - UBTU-22-255030
    - CAT2
    - CCI-001133
    - SRG-OS-000126-GPOS-00066
    - SV-260527r986275_rule
    - SV-260527
    - NIST800-53R4_SC-10
    - ssh
  ansible.builtin.lineinfile:
    path: "{{ ubtu22stig_sshd_config_file }}"
    regexp: ^(?i)(#|)ClientAliveCountMax\s\d*
    line: "ClientAliveCountMax {{ ubtu22stig_sshd_config_clientalivecountmax }}"
    validate: sshd -t -f %s
    mode: 'go-rwx'
  notify: Restart_ssh

- name: MEDIUM | UBTU-22-255035 | PATCH | Ubuntu 22.04 LTS must be configured so that all network connections associated with SSH traffic are terminated after 10 minutes of becoming unresponsive.
  when: ubtu22stig_255035
  tags:
    - UBTU-22-255035
    - CAT2
    - CCI-001133
    - SRG-OS-000163-GPOS-00072
    - SV-260528r970703_rule
    - SV-260528
    - NIST800-53R4_SC-10
    - ssh
  ansible.builtin.lineinfile:
    path: "{{ ubtu22stig_sshd_config_file }}"
    regexp: ^(?i)(#|)ClientAliveInterval\s\d*
    line: "ClientAliveInterval {{ ubtu22stig_sshd_config_clientaliveinterval }}"
    validate: sshd -t -f %s
    mode: 'go-rwx'
  notify: Restart_ssh

- name: MEDIUM | UBTU-22-255045 | PATCH | Ubuntu 22.04 LTS SSH daemon must prevent remote hosts from connecting to the proxy display.
  when: ubtu22stig_255045
  tags:
    - UBTU-22-255045
    - CAT2
    - CCI-000366
    - SRG-OS-000163-GPOS-00072
    - SV-260530r991589_rule
    - SV-260530
    - NIST800-53R4_CM-6
    - ssh
  ansible.builtin.lineinfile:
    path: "{{ ubtu22stig_sshd_config_file }}"
    regexp: ^(?i)(#|)X11UseLocalhost\s\d*
    line: "X11UseLocalhost yes"
    validate: sshd -t -f %s
    mode: 'go-rwx'
  notify: Restart_ssh

- name: MEDIUM | UBTU-22-255050 | PATCH | Ubuntu 22.04 LTS must configure the SSH daemon to use FIPS 140-3-approved ciphers to prevent the unauthorized disclosure of information and/or detect changes to information during transmission.
  when: ubtu22stig_255050
  tags:
    - UBTU-22-255050
    - CAT2
    - CCI-000068
    - CCI-002421
    - CCI-003123
    - SRG-OS-000033-GPOS-00014
    - SRG-OS-000394-GPOS-00174
    - SRG-OS-000424-GPOS-00188
    - SV-260531r958408_rule
    - V-260531
    - NIST800-53R4_AC-17
    - NIST800-53R4_SC-8
    - NIST800-53R4_MA-4
    - ssh
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^Ciphers
    line: "Ciphers {{ ubtu22stig_sshd_config_ciphers | join(',') }}"
    validate: sshd -t -f %s
  notify: Change_requires_reboot

- name: MEDIUM | UBTU-22-255055 | PATCH | Ubuntu 22.04 LTS must configure the SSH daemon to use FIPS 140-3-approved ciphers to prevent the unauthorized disclosure of information and/or detect changes to information during transmission.
  when: ubtu22stig_255055
  tags:
    - UBTU-22-255055
    - CAT2
    - CCI-001453
    - CCI-002421
    - CCI-002890
    - SRG-OS-000250-GPOS-00093
    - SRG-OS-000393-GPOS-00173
    - SRG-OS-000424-GPOS-00188
    - SV-260532r991554_rule
    - V-260532
    - NIST800-53R4_AC-17
    - NIST800-53R4_SC-8
    - NIST800-53R4_MA-4
    - ssh
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^MACs
    line: "MACs {{ ubtu22stig_sshd_config_macs | join(',') }}"
    validate: sshd -t -f %s
  notify: Restart_ssh

- name: MEDIUM | UBTU-22-255055 | PATCH | Ubuntu 22.04 LTS must configure the SSH daemon to use Message Authentication Codes (MACs) employing FIPS 140-3-approved cryptographic hashes to prevent the unauthorized disclosure of information and/or detect changes to information during transmission.
  when: ubtu22stig_255055
  tags:
    - UBTU-22-255055
    - CAT2
    - CCI-001453
    - CCI-002421
    - CCI-002890
    - SRG-OS-000250-GPOS-00093
    - SRG-OS-000393-GPOS-00173
    - SRG-OS-000424-GPOS-00188
    - SV-260532r991554_rule
    - V-260532
    - NIST800-53R4_AC-17
    - NIST800-53R4_SC-8
    - NIST800-53R4_MA-4
    - ssh
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^MACs
    line: "MACs {{ ubtu22stig_sshd_config_macs | join(',') }}"
    validate: sshd -t -f %s
  notify: Change_requires_reboot

- name: MEDIUM | UBTU-22-255060 | PATCH | Ubuntu 22.04 LTS SSH server must be configured to use only FIPS-validated key exchange algorithms.
  when: ubtu22stig_255060
  tags:
    - UBTU-22-255060
    - CAT2
    - CCI-000068
    - SRG-OS-000033-GPOS-00014
    - SV-260533r958408_rule
    - V-260533
    - NIST800-53R4_AC-17
    - ssh
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^KexAlgorithms
    line: "KexAlgorithms {{ ubtu22stig_sshd_config_kex | join(',') }}"
    validate: sshd -t -f %s
  notify: Restart_ssh

- name: MEDIUM | UBTU-22-255065 | PATCH |  Ubuntu 22.04 LTS must use strong authenticators in establishing nonlocal maintenance and diagnostic sessions
  when: ubtu22stig_255065
  tags:
    - UBTU-22-255065
    - CAT2
    - CCI-000877
    - SRG-OS-000125-GPOS-00065
    - SV-260534r958510_rule
    - V-260534
    - NIST800-53R4_MA-4
    - ssh
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^UsePAM
    line: "UsePAM yes"
    validate: sshd -t -f %s
  notify: Restart_ssh
