---

- name: LOW | UBTU-22-215015 | PATCH | Ubuntu 22.04 LTS must have the "chrony" package installed.
  when: ubtu22stig_215015
  tags:
    - UBTU-22-215015
    - CAT3
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-260479r991589_rule
    - V-260479
    - NIST800-53R4_CM-6
    - packages
    - time
  ansible.builtin.package:
    name: chrony
    state: present

- name: LOW | UBTU-22-215020 | PATCH | Ubuntu 22.04 LTS must not have the "systemd-timesyncd" package installed.
  when: ubtu22stig_215020
  tags:
    - UBTU-22-215020
    - CAT3
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-260480r991589_rule
    - V-260480
    - NIST800-53R4_CM-6
    - packages
    - time
  ansible.builtin.package:
    name: systemd-timesyncd
    state: absent

- name: LOW | UBTU-22-215025 | PATCH | Ubuntu 22.04 LTS must not have the "ntp" package installed.
  when: ubtu22stig_215025
  tags:
    - UBTU-22-215025
    - CAT3
    - CCI-000366
    - SRG-OS-000480-GPOS-00227
    - SV-260481r991589_rule
    - V-260481
    - NIST800-53R4_CM-6
    - packages
    - time
  ansible.builtin.package:
    name: ntp
    state: absent
