---

- name: LOW | UBTU-22-214010 | PATCH | Ubuntu 22.04 LTS must be configured so that the Advance Package Tool (APT) prevents the installation of patches, service packs, device drivers, or operating system components without verification they have been digitally signed using a certificate that is recognized and approved by the organization.
  when: ubtu22stig_214010
  tags:
    - UBTU-22-214010
    - CAT3
    - CCI-000000
    - SRG-OS-000366-GPOS-00153
    - SV-260476r986272
    - V-260476
    - NIST800-53R4_NA
    - apt
  block:
    - name: LOW | UBTU-22-214010 | AUDIT | Ubuntu 22.04 LTS must be configured so that the Advance Package Tool (APT) prevents the installation of patches, service packs, device drivers, or operating system components without verification they have been digitally signed using a certificate that is recognized and approved by the organization.
      when: "'/etc/apt/apt.conf.d/01-vendor-ubuntu' in item"
      ansible.builtin.replace:
        path: "{{ item }}"
        regexp: ^(APT::Get::AllowUnauthenticated "true";)
        replace: '#\1'
      with_fileglob:
        - /etc/apt/*

    - name: LOW | UBTU-22-214010 | AUDIT | Ubuntu 22.04 LTS must be configured so that the Advance Package Tool (APT) prevents the installation of patches, service packs, device drivers, or operating system components without verification they have been digitally signed using a certificate that is recognized and approved by the organization.
      ansible.builtin.lineinfile:
        path: /etc/apt/apt.conf.d/01-vendor-ubuntu
        regexp: APT::Get::AllowUnauthenticated
        line: APT::Get::AllowUnauthenticated "true";
