---

- name: "POST | AUDITD | Apply auditd template will only required rules will be added"
  ansible.builtin.template:
    src: etc/audit/rules.d/stig.rules.j2
    dest: /etc/audit/rules.d/stig.rules
    owner: root
    group: root
    mode: 'u-x,go-wx'
  notify:
    - Auditd_immutable_check
    - Audit_immutable_fact
    - Restart_auditd
