---

## metadata for Audit benchmark
benchmark_version: 'v2.2.0'

## Benchmark name used by auditing control role
# The audit variable found at the base
benchmark: UBUNTU22-STIG

# Whether to skip the OS check for supported OS's
skip_os_check: false

ubtu22stig_cat1: true
ubtu22stig_cat2: true
ubtu22stig_cat3: true

# We've defined complexity-high to mean that we cannot automatically remediate
# the rule in question.  In the future this might mean that the remediation
# may fail in some cases.
ubtu22stig_complexity_high: false

# Show "changed" for complex items not remediated per complexity-high setting
# to make them stand out.  "changed" items on a second run of the role would
# indicate items requiring manual review.
ubtu22stig_audit_complex: true

# We've defined disruption-high to indicate items that are likely to cause
# disruption in a normal workflow.  These items can be remediated automatically
# but are disabled by default to avoid disruption.
ubtu22stig_disruption_high: false

# Allow aide check to run - this can be very resource intensive - not good on shared storage multiple hosts
ubtu22stig_allow_aide_check: false

ubtu22stig_workaround_for_disa_benchmark: true

## Unrestricted boot
# Setting this variable to false enables the system to
# boot *without* querying for the bootloader password.
ubtu22stig_ask_passwd_to_boot: true

# tweak role to run in a chroot, such as in kickstart %post script
ubtu22stig_system_is_chroot: "{{ ansible_is_chroot | default(False) }}"

# Set if system uses ipv6
ubtu22stig_system_uses_ipv6: false

# Place to find the container yml file for your environment - /vars/...
container_vars_file: is_container.yml

# Whether to skip the reboot
skip_reboot: true

# system acts or requires router networking options
ubtu22stig_system_is_router: false

# System is based on ec2
system_is_ec2: false

# Whether to purge apt pages when removed
ubtu22stig_purge_apt: false

# Create managed not custom local_facts files
create_benchmark_facts: true
ansible_facts_path: /etc/ansible/facts.d

###
### Settings for associated Audit role using Goss
###

###########################################
### Goss is required on the remote host ###
### vars/audit.yml for other settings  ###

# Allow audit to setup the requirements including installing git (if option chosen and downloading and adding goss binary to system)
setup_audit: false

# enable audits to run - this runs the audit and get the latest content
run_audit: false
# Run heavy tests - some tests can have more impact on a system enabling these can have greater impact on a system
audit_run_heavy_tests: true

## Only run Audit do not remediate
audit_only: false

#############################

# How to retrieve audit binary
# Options are copy or download - detailed settings at the bottom of this file
# you will need to access to either github or the file already downloaded
get_audit_binary_method: download

## if get_audit_binary_method - copy the following needs to be updated for your environment
## it is expected that it will be copied from somewhere accessible to the control node
## e.g copy from ansible control node to remote host
audit_bin_copy_location: /some/accessible/path

# how to get audit files onto host options
# options are git/copy/archive/get_url other e.g. if you wish to run from already downloaded conf
audit_content: git

# If using either archive, copy, get_url:
## Note will work with .tar files - zip will require extra configuration
### If using get_url this is expecting github url in tar.gz format e.g.
### https://github.com/ansible-lockdown/UBUNTU22-STIG-Audit/archive/refs/heads/benchmark-v1.0.0.tar.gz
audit_conf_source: "some path or url to copy from"

# Destination for the audit content to be placed on managed node
# note may not need full path e.g. /opt with the directory being the {{ benchmark }}-Audit directory
audit_conf_dest: "/opt"

# Where the audit logs are stored
audit_log_dir: '/opt'

## Ability to collect and take audit files moving to a centralized location
# This enables the collection of the files from the host
fetch_audit_output: false

# Method of getting,uploading the summary files
## Ensure access and permissions are available for these to occur.
## options are
# fetch - fetches from server and moves to location on the ansible controller (could be a mount point available to controller)
# copy - copies file to a location available to the managed node
audit_output_collection_method: fetch

# Location to put the audit files
audit_output_destination: /opt/audit_summaries/

### Goss Settings ##
####### END ########

#### CAT 1

ubtu22stig_211015: true
ubtu22stig_212010: true
ubtu22stig_215030: true
ubtu22stig_215035: true
ubtu22stig_255010: true
ubtu22stig_255015: true
ubtu22stig_255025: true
ubtu22stig_255040: true
ubtu22stig_271030: true
ubtu22stig_432015: true
ubtu22stig_611060: true
ubtu22stig_611065: true
ubtu22stig_612040: true
ubtu22stig_671010: true

#### CAT 2
## 2XX – System Configuration
ubtu22stig_212015: true
ubtu22stig_213015: true
ubtu22stig_213020: true
ubtu22stig_213025: true
ubtu22stig_214015: true
ubtu22stig_215010: true
ubtu22stig_231010: true
ubtu22stig_232010: true
ubtu22stig_232015: true
ubtu22stig_232020: true
ubtu22stig_232025: true
ubtu22stig_232026: true
ubtu22stig_232027: true
ubtu22stig_232030: true
ubtu22stig_232035: true
ubtu22stig_232040: true
ubtu22stig_232045: true
ubtu22stig_232050: true
ubtu22stig_232055: true
ubtu22stig_232060: true
ubtu22stig_232065: true
ubtu22stig_232070: true
ubtu22stig_232075: true
ubtu22stig_232080: true
ubtu22stig_232085: true
ubtu22stig_232090: true
ubtu22stig_232095: true
ubtu22stig_232100: true
ubtu22stig_232105: true
ubtu22stig_232110: true
ubtu22stig_232115: true
ubtu22stig_232120: true
ubtu22stig_232125: true
ubtu22stig_232130: true
ubtu22stig_232135: true
ubtu22stig_232140: true
ubtu22stig_232145: true
ubtu22stig_251010: true
ubtu22stig_251015: true
ubtu22stig_251020: true
ubtu22stig_251025: true
ubtu22stig_251030: true
ubtu22stig_253010: true
ubtu22stig_255020: true
ubtu22stig_255030: true
ubtu22stig_255035: true
ubtu22stig_255045: true
ubtu22stig_255050: true
ubtu22stig_255055: true
ubtu22stig_255060: true
ubtu22stig_255065: true
ubtu22stig_271010: true
ubtu22stig_271015: true
ubtu22stig_271020: true
ubtu22stig_271025: true
ubtu22stig_291010: true
ubtu22stig_291015: true
## 4XX – User Configuration
ubtu22stig_411010: true
ubtu22stig_411015: true
ubtu22stig_411025: true
ubtu22stig_411030: true
ubtu22stig_411035: true
ubtu22stig_411040: true
ubtu22stig_412025: true
ubtu22stig_412030: true
ubtu22stig_412035: true
ubtu22stig_431010: true
ubtu22stig_431015: true
ubtu22stig_432010: true
## 6xx - Authentication, Authorization and Accounting
ubtu22stig_611010: true
ubtu22stig_611015: true
ubtu22stig_611020: true
ubtu22stig_611025: true
ubtu22stig_611030: true
ubtu22stig_611035: true
ubtu22stig_611040: true
ubtu22stig_611045: true
ubtu22stig_611055: true
ubtu22stig_611070: true
ubtu22stig_612010: true
ubtu22stig_612015: true
ubtu22stig_612020: true
ubtu22stig_612025: true
ubtu22stig_612030: true
ubtu22stig_612035: true
ubtu22stig_631010: true
ubtu22stig_651010: true
ubtu22stig_651015: true
ubtu22stig_651020: true
ubtu22stig_651025: true
ubtu22stig_651030: true
ubtu22stig_652010: true
ubtu22stig_652015: true
ubtu22stig_653010: true
ubtu22stig_653015: true
ubtu22stig_653030: true
ubtu22stig_653045: true
ubtu22stig_653050: true
ubtu22stig_653055: true
ubtu22stig_653060: true
ubtu22stig_653065: true
ubtu22stig_653070: true
ubtu22stig_653075: true
ubtu22stig_654010: true
ubtu22stig_654015: true
ubtu22stig_654020: true
ubtu22stig_654025: true
ubtu22stig_654030: true
ubtu22stig_654035: true
ubtu22stig_654040: true
ubtu22stig_654045: true
ubtu22stig_654050: true
ubtu22stig_654055: true
ubtu22stig_654060: true
ubtu22stig_654065: true
ubtu22stig_654070: true
ubtu22stig_654075: true
ubtu22stig_654080: true
ubtu22stig_654085: true
ubtu22stig_654090: true
ubtu22stig_654095: true
ubtu22stig_654100: true
ubtu22stig_654105: true
ubtu22stig_654110: true
ubtu22stig_654115: true
ubtu22stig_654120: true
ubtu22stig_654125: true
ubtu22stig_654130: true
ubtu22stig_654135: true
ubtu22stig_654140: true
ubtu22stig_654145: true
ubtu22stig_654150: true
ubtu22stig_654155: true
ubtu22stig_654160: true
ubtu22stig_654165: true
ubtu22stig_654170: true
ubtu22stig_654175: true
ubtu22stig_654180: true
ubtu22stig_654185: true
ubtu22stig_654190: true
ubtu22stig_654195: true
ubtu22stig_654200: true
ubtu22stig_654205: true
ubtu22stig_654210: true
ubtu22stig_654215: true
ubtu22stig_654220: true
ubtu22stig_654225: true
ubtu22stig_654230: true
ubtu22stig_654235: true

#### CAT 3
ubtu22stig_213010: true
ubtu22stig_214010: true
ubtu22stig_215015: true
ubtu22stig_215020: true
ubtu22stig_215025: true
ubtu22stig_252010: true
ubtu22stig_252015: true
ubtu22stig_252020: true
ubtu22stig_411045: true
ubtu22stig_412010: true
ubtu22stig_412015: true
ubtu22stig_412020: true
ubtu22stig_631015: true
ubtu22stig_651035: true
ubtu22stig_653020: true
ubtu22stig_653025: true
ubtu22stig_653035: true
ubtu22stig_653040: true

### CONTROLS

##################################
### 2XX – System Configuration ###
##################################

## 212xxx Bootloader/Grub settings
ubtu22stig_bootloader_password_hash: 'grub.pbkdf2.sha512.changethispassword'  # pragma: allowlist secret
ubtu22stig_set_bootloader_password: false
ubtu22stig_grub2_path: /etc/grub2.cfg

## 213xxx - Kernel
ubtu22stig_sysctl_file_default: /etc/sysctl.d/stig_kernel.conf
ubtu22stig_sysctl_kernel_conf: "{{ ubtu22stig_sysctl_file_default }}"

# 215xxx
## Chrony
ubtu22stig_time_synchronization_servers:
- 'tick.usno.navy.mil'
- 'tock.usno.navy.mil'
- 'ntp2.usno.navy.mil'
ubtu22stig_chrony_server_options: "iburst maxpoll 16"  # Max Settings is maxpoll 16

## 253xxx
ubtu22stig_sysctl_network_conf: "{{ ubtu22stig_sysctl_file_default }}"

## 255xxx - Network - SSHD
ubtu22stig_ssh_required: true
ubtu22stig_sshd_config_file: /etc/ssh/sshd_config
ubtu22stig_sshd_config_clientalivecountmax: 1
ubtu22stig_sshd_config_clientaliveinterval: 600  # max 600
ubtu22stig_sshd_config_ciphers: "{{ ubtu22stig_dod_ciphers }}"
ubtu22stig_sshd_config_macs: "{{ ubtu22stig_dod_macs }}"
ubtu22stig_sshd_config_kex: "{{ ubtu22stig_dod_kex }}"

## Banner
ubtu22stig_logon_banner: "{{ ubtu22stig_workaround_for_disa_benchmark | ternary(
        ubtu22stig_logon_banner_nice | regex_replace('(?s)(?<!\\n)\\n(?!(\n|$))', ' '),
        ubtu22stig_logon_banner_nice) }}"
ubtu22stig_logon_banner_nice: |
    You are accessing a U.S. Government (USG) Information System (IS) that is
    provided for USG-authorized use only.

    By using this IS (which includes any device attached to this IS), you consent
    to the following conditions:

    -The USG routinely intercepts and monitors communications on this IS for
    purposes including, but not limited to, penetration testing, COMSEC monitoring,
    network operations and defense, personnel misconduct (PM), law enforcement
    (LE), and counterintelligence (CI) investigations.

    -At any time, the USG may inspect and seize data stored on this IS.

    -Communications using, or data stored on, this IS are not private, are subject
    to routine monitoring, interception, and search, and may be disclosed or used
    for any USG-authorized purpose.

    -This IS includes security measures (e.g., authentication and access controls)
    to protect USG interests--not for your personal benefit or privacy.

    -Notwithstanding the above, using this IS does not constitute consent to PM, LE
    or CI investigative searching or monitoring of the content of privileged
    communications, or work product, related to personal representation or services
    by attorneys, psychotherapists, or clergy, and their assistants. Such
    communications and work product are private and confidential. See User
    Agreement for details.

# 27xxxx
ubtu22stig_sudo_group_required:
- vagrant

### 271xxx - Gnome Desktop
### Graphical/Gnome interface required
ubtu22stig_gui: "{{ ubtu22_gnome_present.stat.exists | default(false) }}"

################################
### 4xx - User Configuration ###
################################

### 411xxx - User Configuration
### ACCOUNTS ###
ubtu22stig_pass_minlen: '15'  # 15 is minimum for STIG
ubtu22stig_pass_difok: '8'  # 8 is minimum for STIG
ubtu22stig_pass_max_days: '60'
ubtu22stig_pass_min_days: '1'
ubtu22stig_user_inactive_days: '35'
# Faillock settings
ubtu22stig_faillock_deny: '3'  # 3 or less but not 0
ubtu22stig_faillock_fail_interval: '900'  # 900 or less is required
ubtu22stig_faillock_unlock_time: '0'

# 412xxx Session
# faildelay
ubtu22stig_faildelay: 4000000  # 4000000 is the minimum value = 4 seconds
# maxlogins maximum number of logins per user
ubtu22stig_maxlogins: 10

###########################################################
### 6xx - Authentication, Authorization, and Accounting ###
###########################################################

# 611xxx
# ubtu22stig_passwd_hash_algo is the hashing algorithm used - STIG required SHA512 - default is newer yescrypt
ubtu22stig_passwd_hash_algo: sha512  # pragma: allowlist secret
# Set pam as well as login defs if PAM is required
ubtu22stig_passwd_setpam_hash_algo: false

# 612xxx
# Section 612xxx is for smartcards configurations these require further configurations before applying STiG settings
ubtu22stig_configure_multifactor_auth: false

# 651xxx
### Aide
ubtu22stig_use_aide: true
ubtu22stig_aide_cron_file: /etc/cron.daily/aide  # NOTE the path may change if not running daily
ubtu22stig_aide_cron:
  day: '*'
  hour: '4'
  minute: '30'
  job: '/usr/sbin/aide --check | /bin/mail -s "$HOSTNAME - Daily aide integrity check run" root@sysname.mil'
  name: 'Aide Job runs Daily at 0430'

# 653xxx
### AUDITD
ubtu22stig_audit_log_filesystem: /var/log/audit
ubtu22stig_auditd_disk_full_action: HALT  # Can be one of "SYSLOG", "SINGLE", or "HALT"
ubtu22stig_auditd_log_group: root
ubtu22stig_auditd_email_acct: root
ubtu22stig_auditd_space_left: 25%
ubtu22stig_auditd_space_left_action: EMAIL  # Can be set to exec if running script to inform ISSO

# Adjust to match remote syslog server configuration
ubtu22stig_remotelog_server_address: 10.10.10.10
